### ISSUE TITLE
Wiring of load cells

### ISSUE THREAD

**Issue by flyer007** [tatobari/hx711py#20]
First off let me thank you for the great code!  Worked fine after my son figured out the schematic was wrong on Amazon.  Be careful out there.  Attached is correct one.  
![714HHy7QEYL _SL1500_](https://user-images.githubusercontent.com/9012850/54572960-70692c00-49c0-11e9-95f6-4fd21adf8986.jpg)

My son is using this to monitor weight placed on a structure that sends an MQTT message when weight reaches over X amount.  He used 4 50Kg load cells and some rubber crush pads to get upto 500lbs.

**Comment by tatobari** [comment]
Tha k you for your post. This code is intended to be used with different HX711 implementations and different load cell layouts. It's up to the developer to decide what to go with.

If there are any hookup doubts, I can only recommend people to start by checking Sparkfun's tutorials and products. They are great.

In your case, since you are combining 3-wire load cells, which are incomplete Wheatstone bridges unlike 4-wire load cells which are complete Wheatstone bridges, I'd have used a Load Cell Combinator.

https://learn.sparkfun.com/tutorials/getting-started-with-load-cells/combinator-basics

https://www.sparkfun.com/prod
